spring.application.name=rbac
spring.data.mongodb.uri=mongodb://localhost:27017/rbac_db
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false



server.port=8080