spring.application.name=rbac

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/rbac_db



server.port=8080
# Logging (Helpful for debugging security)
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

